### ISSUE TITLE
adding mysql to the docker

### ISSUE THREAD

**Issue by mouadFahsi** [mrsan22/Angular-Flask-Docker-Skeleton#1]
Hi, Great work on this Docker file it's working like a charm,
i'm new to this Docker and Containers stuff so i would like to add mysql to it but i think i've crashed every thing.
can you help with that. and thanks in advance

**Comment by mrsan22** [comment]
Hi, Thanks for trying this project. And if you have not figured out yet, soon I am going to release another project built on top of this skeleton with database support.

**Comment by mrsan22** [comment]
I have added PostgreSQL support in the new version. Thanks!
