### ISSUE TITLE
Flask container fail to start

### ISSUE THREAD

**Issue by Antarius225** [mrsan22/Angular-Flask-Docker-Skeleton#6]
The flask container is unable to start.
![image](https://user-images.githubusercontent.com/7151943/52976437-c949a280-33c9-11e9-9a65-17e15154b061.png)
When I try to see what's happening in the flask container by displaying logs :
![image](https://user-images.githubusercontent.com/7151943/52976464-e4b4ad80-33c9-11e9-9c35-3902ca0a67ed.png)

**Comment by Antarius225** [comment]
Docker version 18.03.0-ce, build 0520e24302
on Windows 10

**Comment by manjurulcis** [comment]
Same here on windows 10
![image](https://user-images.githubusercontent.com/4739315/55846873-fdcb1680-5b4f-11e9-9461-3448c74a9883.png)

**Comment by devturner** [comment]
Same error, any work around?

**Comment by mrsan22** [comment]
Sorry for late response. This should be fixed now.
